name: build-if-tag

on:
  push:
    tags:
      - "v*"

env:
  APP: amneziawg-go

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ARM64 image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ARM64 image (export tarball)
        uses: docker/build-push-action@v5
        with:
          push: false
          platforms: linux/arm64
          outputs: type=docker,dest=./${{ env.APP }}-arm64.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP }}-arm64
          path: ./${{ env.APP }}-arm64.tar
